Update checks.yaml

diff --git a/.github/workflows/checks.yaml b/.github/workflows/checks.yaml
--- a/.github/workflows/checks.yaml
+++ b/.github/workflows/checks.yaml
@@ -1,7 +1,5 @@
 name: status_check
-on: 
-  pull_request:
-    branches: [main]
+on: [push, pull_request]
 
 jobs:
   check:
@@ -15,14 +13,20 @@ jobs:
       #       #path: './bar'
       - name: check_remote
         run: |
-          echo "GH variables:"
-          echo ${GITHUB_HEAD_REF}
-          echo ${GITHUB_REF_NAME}
-          echo ${GITHUB_REPOSITORY}
-          echo ${GITHUB_REPOSITORY_OWNER} 
-          echo "GITHUB_HEAD_REF = ${GITHUB_HEAD_REF}"
-          curl -s "https://api.github.com/repos/ait-dmirian/public-test/pulls?base=main&state=all&head=ait-dmirian:${GITHUB_HEAD_REF}" > result.txt
-          pr_name=$(grep "ait-dmirian:${GITHUB_HEAD_REF}" result.txt)
-          echo "Echo: $pr_name"
-          grep "state" result.txt
-          if [ "$pr_name" ]; then echo "The PR name is: $pr_name"; else echo "There is no PR for ait-dmirian:${GITHUB_HEAD_REF}" && exit 1;  fi
+          # ls -la && pwd 
+          # response=$(curl --write-out '%{http_code}' --silent --output /dev/null https://api.github.com/repos/ait-dmirian/public-test/pulls/2/merge)
+          # echo $response
+          # if [ "$response" != 204 ]; then exit 1; fi
+          # #gh pr list
+          #curl -s 'https://api.github.com/repos/ait-dmirian/public-test/pulls?base=main&state=any&head=ait-dmirian:ait-dmirian-patch-3' | grep "ait-dmirian:ait-dmirian-patch-3"
+          #if [ "$?" != 0 ]; then exit 1; fi
+          #echo ${GITHUB_REF_NAME}
+          #echo ${GITHUB_REPOSITORY}
+          #echo curl -s "https://api.github.com/repos/ait-dmirian/public-test/pulls?base=main&state=any&head=ait-dmirian:${GITHUB_REF_NAME}"
+          # if grep won't find anything then resul=nothign will fail the job
+          #result=$(curl -s "https://api.github.com/repos/ait-dmirian/public-test/pulls?base=main&state=all&head=ait-dmirian:${GITHUB_REF_NAME}" | grep "ait-dmirian:${GITHUB_REF_NAME}") 
+          # If result is not empty echo it, otherwise exit with error and fail job 
+          #[[ ! -z "$result" ]] && echo $result || exit 1           
+          curl -s "https://api.github.com/repos/ait-dmirian/public-test/pulls?base=main&state=all&head=ait-dmirian:${GITHUB_REF_NAME}" > result.txt
+          pr_name=$(grep "ait-dmirian:${GITHUB_REF_NAME}" result.txt)
+          if [ "$pr_name" ]; then echo "$pr_name"; else echo "There is no PR for ait-dmirian:${GITHUB_REF_NAME}" && exit 1;  fi
